import type { PrefabCatalogItem } from "./prefabTypes";

const CATALOG: PrefabCatalogItem[] = [
  {
    code: "COV_L_2x1",
    collider: "box",
    size: { x: 2, y: 0.9, z: 1 },
    color: 0x4f6a83,
    blocksLineOfSight: false,
    blocksProjectile: true,
    blocksMovement: true,
    minimapLayer: "cover",
    receivesShadow: true,
    castsShadow: true,
  },
  {
    code: "COV_H_3x1",
    collider: "box",
    size: { x: 3, y: 1.8, z: 1 },
    color: 0x46617b,
    blocksLineOfSight: true,
    blocksProjectile: true,
    blocksMovement: true,
    minimapLayer: "cover",
    receivesShadow: true,
    castsShadow: true,
  },
  {
    code: "WALL_6",
    collider: "box",
    size: { x: 6, y: 2.2, z: 0.8 },
    color: 0x364a62,
    blocksLineOfSight: true,
    blocksProjectile: true,
    blocksMovement: true,
    minimapLayer: "wall",
    receivesShadow: true,
    castsShadow: true,
  },
  {
    code: "BUSH_S",
    collider: "trigger",
    size: { x: 3, y: 1.4, z: 3 },
    color: 0x2c7a46,
    opacity: 0.55,
    blocksLineOfSight: false,
    blocksProjectile: false,
    blocksMovement: false,
    minimapLayer: "bush",
    receivesShadow: true,
  },
  {
    code: "BUSH_M",
    collider: "trigger",
    size: { x: 5, y: 1.6, z: 5 },
    color: 0x2f8f53,
    opacity: 0.58,
    blocksLineOfSight: false,
    blocksProjectile: false,
    blocksMovement: false,
    minimapLayer: "bush",
    receivesShadow: true,
  },
  {
    code: "BUSH_L",
    collider: "trigger",
    size: { x: 7, y: 1.8, z: 7 },
    color: 0x34a35d,
    opacity: 0.6,
    blocksLineOfSight: false,
    blocksProjectile: false,
    blocksMovement: false,
    minimapLayer: "bush",
    receivesShadow: true,
  },
  {
    code: "RAMP_10",
    collider: "ramp",
    size: { x: 2.8, y: 1.2, z: 10 },
    color: 0x566577,
    blocksLineOfSight: false,
    blocksProjectile: false,
    blocksMovement: false,
    minimapLayer: "utility",
    receivesShadow: true,
    castsShadow: true,
  },
  {
    code: "PAD_JUMP",
    collider: "trigger",
    size: { x: 2, y: 0.25, z: 2 },
    color: 0x56c5ff,
    blocksLineOfSight: false,
    blocksProjectile: false,
    blocksMovement: false,
    minimapLayer: "utility",
  },
  {
    code: "OBJ_CORE",
    collider: "trigger",
    size: { x: 4, y: 2, z: 4 },
    color: 0xc983ff,
    blocksLineOfSight: false,
    blocksProjectile: false,
    blocksMovement: false,
    minimapLayer: "objective",
  },
  {
    code: "OBJ_ZONE",
    collider: "trigger",
    size: { x: 9, y: 0.2, z: 9 },
    color: 0x72c5ff,
    opacity: 0.42,
    blocksLineOfSight: false,
    blocksProjectile: false,
    blocksMovement: false,
    minimapLayer: "objective",
  },
  {
    code: "OBJ_PAYLOAD_PATH",
    collider: "trigger",
    size: { x: 1, y: 0.2, z: 1 },
    color: 0xffbd5e,
    opacity: 0.65,
    blocksLineOfSight: false,
    blocksProjectile: false,
    blocksMovement: false,
    minimapLayer: "path",
  },
];

const CATALOG_BY_CODE = new Map<string, PrefabCatalogItem>(CATALOG.map((item) => [item.code, item]));

export function getPrefabCatalogItem(code: string): PrefabCatalogItem | null {
  return CATALOG_BY_CODE.get(code) ?? null;
}

export function listPrefabCatalog(): readonly PrefabCatalogItem[] {
  return CATALOG;
}
