export const OPCODES = {
  C2S_HELLO: "C2S_HELLO",
  C2S_INPUT: "C2S_INPUT",
  C2S_PING: "C2S_PING",
  C2S_ACK: "C2S_ACK",
  S2C_WELCOME: "S2C_WELCOME",
  S2C_MATCH_START: "S2C_MATCH_START",
  S2C_SNAPSHOT_BASE: "S2C_SNAPSHOT_BASE",
  S2C_SNAPSHOT_DELTA: "S2C_SNAPSHOT_DELTA",
  S2C_EVENT: "S2C_EVENT",
  S2C_MATCH_END: "S2C_MATCH_END",
} as const;

export type Opcode = (typeof OPCODES)[keyof typeof OPCODES];
